"""


Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nu@rt+zf*-g)iuc#rqf!&o**r^l@l-1ml0gt^nrh6)+o&zc4@$'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','www.lemall.site','127.0.0.1','192.168.92.82']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.verifications',
    'apps.oauth',
    'apps.areas',
    'apps.goods',
    'apps.contents',
    'haystack',
    'django_crontab',
    'apps.carts',
    'apps.orders',
    'apps.Management',
    'apps.RecomSys'

]
#替换系统的USER模型
AUTH_USER_MODEL='users.User'
#跨域添加白名单
# CORS
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://www.lemall.site:8000',
    'http://192.168.92.82:8000',
]
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
'''celery配置'''
CELERY_BROKER_URL = 'redis://localhost:6379/15'
# 任务超时时间（例如 30 分钟）
CELERY_TASK_TIME_LIMIT = 30 * 60
# 任务追踪开始
CELERY_TASK_TRACK_STARTED = True


ROOT_URLCONF = 'lemall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lemall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'127.0.0.1',
    'PORT':'3306',
        'USER':'root',
        'PASSWORD':'root',
        'NAME': 'meiduo_mail',
    },
    'uba': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'uba',  # 替换为你的数据库名
        'USER': 'root',  # 替换为你的 MySQL 用户名
        'PASSWORD': 'root',  # 替换为你的密码
        'HOST': '127.0.0.1',  # 数据库地址，本机就是 127.0.0.1
        'PORT': '3306',  # 默认 MySQL 端口
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}
X_FRAME_OPTIONS = 'ALLOWALL'

#django-redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
,
"session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
"code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
"history": { #用于保存用户浏览记录数据
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
"carts": { #用于保存购物车数据
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
},
"recommend": { #用于保存推荐商品的数据
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/5",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
},
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/manage/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/BigDataVisualization/BehavioralPath'),
    os.path.join(BASE_DIR, 'frontend/BigDataVisualization/dashboard'),
    os.path.join(BASE_DIR, 'frontend/BigDataVisualization/TimeSeries'),
    os.path.join(BASE_DIR, 'frontend/BigDataVisualization/echarts'),
    os.path.join(BASE_DIR, 'frontend/BigDataVisualization/RFM'),
    os.path.join(BASE_DIR, 'frontend/front_end_pc'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/css'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/goods'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/images'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/static/isso'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/js'),
os.path.join(BASE_DIR, 'frontend/front_end_pc/static'),
]
#日志
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            'level':'INFO',
            'class':'logging.handlers.RotatingFileHandler',
            "filename":os.path.join(BASE_DIR, "logs/lemall.log"),
            'maxBytes':300*1024 *1024,
            'backupCount': 10,
            'formatter':'verbose'
},
    },
    "loggers": {
        "django": {
            "handlers": ["console","file"],
            "propagate": True,
            "level":'INFO'
        },

    },
}
#QQ登录参数
GITEE_CLIENT_ID='b567b3ee312c21b489c265407cd918b742a301dd87040849296b73c38cb74647'
GITEE_CLIENT_SECRET='6d579391a77cb71f2c3b850ebdfbc4a415729fd1a30e4ed130bc3ad3fe203d72'
GITEE_REDIRECT_URI='http://localhost:8000/manage/oauth_callback.html'
#邮箱配置
#  让django的哪个类来发送邮件
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 邮件服务器的主机和端口号
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25

# 使用我的 163服务器 和 授权码
#发送邮件的邮箱
EMAIL_HOST_USER = 'shenmu_ovo@163.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'HWciBtuMM9EGBtV5'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DEFAULT_FILE_STORAGE = 'utils.fastdfs.storage.MyStorage'
FDFS_BASE_URL = 'http://image.lemall.site:8888/'

#haystack
#需要添加一个设置来指示您的站点配置文件将存放在何处以及使用哪个后端
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://192.168.92.82:9200/',
        'INDEX_NAME': 'meiduo',
    },
}

# 设置搜索 每页返回的记录条数
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 5

#定时
CRONJOBS = [
    ('*/1 * * * *','apps.contents.crons.generic_lemall_index','>> ' + os.path.join(BASE_DIR, 'logs/crontab.log'))

]
#crontab解决中文配置问题
CRONTAB_COMMAND_PREFIX='LANG_ALL=zh_cn.UTF-8'