# Generated by Django 4.2.19 on 2025-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='tb_areas',
        ),
    ]
