# Generated by Django 4.2.19 on 2025-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateHourBehavior',
            fields=[
                ('dates', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hours', models.CharField(max_length=2)),
                ('pv', models.IntegerField()),
                ('cart', models.IntegerField()),
                ('fav', models.IntegerField()),
                ('buy', models.IntegerField()),
            ],
            options={
                'verbose_name': '每小时用户行为数据',
                'verbose_name_plural': '每小时用户行为数据',
                'db_table': 'date_hour_behavior',
                'ordering': ['dates', 'hours'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathResult',
            fields=[
                ('path_type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'path_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RFMModel',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('recent', models.DateField()),
                ('fscore', models.IntegerField()),
                ('rscore', models.IntegerField()),
                ('class_field', models.CharField(db_column='class', max_length=20)),
            ],
            options={
                'db_table': 'rfm_model',
                'managed': False,
            },
        ),
    ]
