# Generated by Django 4.2.19 on 2025-03-19 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAuthQQUser',
            new_name='OAuthGITEEUser',
        ),
        migrations.AlterModelOptions(
            name='oauthgiteeuser',
            options={'verbose_name': '登录用户数据', 'verbose_name_plural': '登录用户数据'},
        ),
        migrations.AlterModelTable(
            name='oauthgiteeuser',
            table='tb_oauth_gitee',
        ),
    ]
